name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and test frontend
        run: pnpm zip
        
      - name: Get metadata
        id: metadata
        run: |
          sudo apt-get install jq

          export VERSION=$(cat package.json | jq -r .version)
          export ARTIFACT=$(cat package.json | jq -r .name).zip

          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=archive::${ARTIFACT}"

          echo ::set-output name=github-tag::${GITHUB_REF#refs/*/}


      - name: Check package version
        run: if [ "v${{ steps.metadata.outputs.version }}" != "${{ steps.metadata.outputs.github-tag }}" ]; then printf "\033[0;31mVersion doesn't match tag name\033[0m\n"; exit 1; fi

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false

      - name: Add plugin to release
        id: upload-plugin-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/${{ steps.metadata.outputs.archive }}
          asset_name: ${{ steps.metadata.outputs.archive }}
          asset_content_type: application/zip
